Repository BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem, pull requests merged in 2024-04, with the labels that each got.

#3 Chore: Created Landing Page
  landing-page.php
  src/images/logos/acap.png
  src/images/logos/aeces.png
  src/images/logos/comelec.png
  src/images/logos/elite.png
  src/images/logos/give.png
  src/images/logos/jehra.png
  src/images/logos/jmap.png
  src/images/logos/jpia.png
  src/images/logos/piie.png
  src/images/logos/pup-src.png
  src/images/logos/sco.png
  src/images/resc/BG.png
  src/styles/core.css
  src/styles/dist/landing.css
  src/styles/scss/style.scss
  src/styles/style.css
Labels: enhancement

#4 AT7-64-Landing Page Backend
  landing-page.php
  src/includes/classes/db-config.php
  src/includes/classes/db-connector.php
  src/includes/classes/landing-page-controller.php
  src/includes/session-handler.php
  src/index.php
  src/landing-page.php
Labels: enhancement

#6 style: initial front-end design of ballot forms
  ballot-forms.php
  src/styles/orgs/give.css
Labels: enhancement

#7 style: updated org color schemes
  src/styles/core.css
  src/styles/orgs/acap.css
  src/styles/orgs/aeces.css
  src/styles/orgs/elite.css
  src/styles/orgs/give.css
  src/styles/orgs/jehra.css
  src/styles/orgs/jmap.css
  src/styles/orgs/piie.css
  src/styles/orgs/sco.css
Labels: enhancement

#12 fix: Change relative file paths of stylesheets, images, and javascripts.
  src/result-generation.php
Labels: bug

#13 Update Sidebar, Header, and Components with Revamped UI & Branding
  src/images/resc/ivote-favicon.png
  src/images/resc/ivote-logo.png
  src/includes/components/sidebar.php
  src/scripts/feather.js
  src/scripts/script.js
  src/styles/scss/style.scss
  src/styles/style.css
  src/styles/style.css.map
  vendor/node_modules/bootstrap/css/bootstrap.css
  vendor/node_modules/bootstrap/css/bootstrap.css.map
  vendor/temps/blank.php
  vendor/temps/sidebar.php
Labels: enhancement, help wanted

#15 New landing page/development
  src/landing-page.php
  src/styles/dist/landing.css
  src/voter-login.php
Labels: bug

#16 feat: AT1-53 added feedback and suggestion page
  src/feedback-suggestion.php
  src/styles/orgs/give.css
Labels: enhancement

#17 fix: AT1-55 ballot forms moved to src folder
  ballot-forms.php
  src/ballot-forms.php
  src/feedback-suggestion.php
  src/styles/orgs/give.css
Labels: help wanted, question

#30 Dynamic CSS for each organization login page
  src/admindashboard.php
  src/ballot-forms.php
  src/includes/classes/landing-page-controller.php
  src/includes/classes/voter-login-class.php
  src/includes/classes/voter-login-controller.php
  src/includes/organization-list.php
  src/includes/session-handler.php
  src/landing-page.php
  src/styles/scss/candidate-position.css
  src/styles/scss/configuration.css
  src/styles/scss/core.css
  src/styles/scss/font-montserrat.css
  src/styles/scss/style.css
  src/styles/scss/voting-guideline.css
  src/voter-login-inc.php
  src/voter-login.php
  src/voter-logout.php
Labels: bug, enhancement, released

#34 style: updated the landing and login page
  src/images/resc/iVOTE-Landing2.png
  src/images/resc/iVOTE4.png
  src/images/resc/landing-background.png
  src/landing-page.php
  src/styles/dist/landing.css
  src/voter-login.php
Labels: enhancement

#35 Login authentication and session-based class
  src/includes/classes/session-manager.php
  src/includes/classes/voter-login-class.php
  src/landing-page.php
  src/voter-login.php
  src/voter-logout.php
Labels: enhancement

#41 Create Footer, Add Session Exchange and Responsiveness
  src/images/resc/icons/facebook.png
  src/images/resc/icons/instagram.png
  src/images/resc/icons/twitter.png
  src/includes/components/footer.php
  src/includes/components/sidebar.php
  src/includes/organization-list.php
  src/includes/session-exchange.php
  src/includes/session-handler.php
  src/scripts/script.js
  src/styles/core.css
  src/styles/orgs/acap.css
  src/styles/orgs/aeces.css
  src/styles/orgs/elite.css
  src/styles/orgs/give.css
  src/styles/orgs/jehra.css
  src/styles/orgs/jmap.css
  src/styles/orgs/jpia.css
  src/styles/orgs/piie.css
  src/styles/orgs/sco.css
  src/styles/style.css
  vendor/node_modules/bootstrap/dist/css/bootstrap.css
  vendor/node_modules/bootstrap/dist/css/bootstrap.min.css
  vendor/temps/blank-code.php
Labels: bug, enhancement, impact alert

#37 feat: AT4-44 added backend to display data from database according to…
  src/result-generation.php
Labels: enhancement, outdated

#45 Login and logout
  src/includes/classes/voter-login-class.php
  src/includes/classes/voter-login-controller.php
  src/landing-page.php
  src/voter-login.php
  src/voter-logout.php
Labels: enhancement

#44 feat: AT2-108-Added UI changes to admindashboard, dynamic information…
  src/admindashboard.php
  src/images/resc/Dashboard/Configuration/acap-config.png
  src/images/resc/Dashboard/Configuration/aeces-config.png
  src/images/resc/Dashboard/Configuration/elite-config.png
  src/images/resc/Dashboard/Configuration/give-config.png
  src/images/resc/Dashboard/Configuration/jehra-config.png
  src/images/resc/Dashboard/Configuration/jmap-config.png
  src/images/resc/Dashboard/Configuration/jpia-config.png
  src/images/resc/Dashboard/Configuration/piie-config.png
  src/images/resc/Dashboard/Configuration/sco-config.png
  src/images/resc/Dashboard/Manage Acc/acap-manage-accs.png
  src/images/resc/Dashboard/Manage Acc/aeces-manage-accs.png
  src/images/resc/Dashboard/Manage Acc/elite-manage-accs.png
  src/images/resc/Dashboard/Manage Acc/give-manage-accs.png
  src/images/resc/Dashboard/Manage Acc/jehra-manage-accs.png
  src/images/resc/Dashboard/Manage Acc/jmap-manage-accs.png
  src/images/resc/Dashboard/Manage Acc/jpia-manage-accs.png
  src/images/resc/Dashboard/Manage Acc/piie-manage-accs.png
  src/images/resc/Dashboard/Manage Acc/sco-manage-accs.png
  src/images/resc/Dashboard/Reports/acap-reports.png
  src/images/resc/Dashboard/Reports/aeces-reports.png
  src/images/resc/Dashboard/Reports/elite-reports.png
  src/images/resc/Dashboard/Reports/give-reports.png
  src/images/resc/Dashboard/Reports/jehra-reports.png
  src/images/resc/Dashboard/Reports/jmap-reports.png
  src/images/resc/Dashboard/Reports/jpia-reports.png
  src/images/resc/Dashboard/Reports/piie-reports.png
  src/images/resc/Dashboard/Reports/sco-reports.png
  src/includes/fetch-all-candidates.php
  src/includes/fetch-candidates.php
  src/scripts/admin_dashboard.js
  src/styles/admin_dashboard.css
Labels: enhancement

#47 Created Voter's Account Management Module
  src/images/resc/check-animation.gif
  src/images/resc/folder-empty.png
  src/includes/classes/query-handler.php
  src/includes/components/sidebar.php
  src/manage-acc.php
  src/manage-voters.php
  src/scripts/manage-voters.js
  src/styles/core.css
  src/styles/manage-voters.css
  src/styles/orgs/acap.css
  src/styles/orgs/aeces.css
  src/styles/orgs/elite.css
  src/styles/orgs/give.css
  src/styles/orgs/jehra.css
  src/styles/orgs/jmap.css
  src/styles/orgs/jpia.css
  src/styles/orgs/piie.css
  src/styles/orgs/sco.css
  src/styles/style.css
  src/styles/tables.css
  src/submission_handlers/manage-acc.php
  src/submission_handlers/validate-acc.php
  src/user_data/acap/candidate_imgs/mingkyu.jpg
  src/user_data/acap/cor/RegCert.pdf
  src/user_data/aeces/candidate_imgs/mingkyu.jpg
  src/user_data/aeces/cor/RegCert.pdf
  src/user_data/elite/candidate_imgs/mingkyu.jpg
  src/user_data/elite/cor/RegCert.pdf
  src/user_data/give/candidate_imgs/mingkyu.jpg
  src/user_data/give/cor/RegCert.pdf
  src/user_data/jehra/candidate_imgs/mingkyu.jpg
  src/user_data/jehra/cor/RegCert.pdf
  src/user_data/jmap/candidate_imgs/mingkyu.jpg
  src/user_data/jmap/cor/RegCert.pdf
  src/user_data/jpia/candidate_imgs/mingkyu.jpg
  src/user_data/jpia/cor/RegCert.pdf
  src/user_data/piie/candidate_imgs/mingkyu.jpg
  src/user_data/piie/cor/RegCert.pdf
  src/user_data/sco/candidate-imgs/mingkyu.jpg
  src/validate-voter.php
  vendor/node_modules/bootstrap/dist/css/bootstrap.min.css
Labels: enhancement

#54 Ballot forms, feedback and suggestions, and end point
  src/ballot-forms.php
  src/end-point.php
  src/feedback-suggestions.php
  src/images/resc/end-point/jpia-endpoint.png
  src/includes/insert-feedback.php
  src/includes/insert-vote.php
  src/styles/ballot-forms.css
  src/styles/feedback-suggestions.css
Labels: released, patch
