Repository BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem, pull requests merged in 2024-05, with the labels that each got.

#53 Adding sorting function in descending order to candidates position and session of organization
  src/result-generation.php
  src/styles/result.css
Labels: released, patch

#48 AT6-98: Toggle Password Visibility
  src/forgot-password.php
  src/images/logos/jmap.png
  src/includes/send-password-reset.php
  src/landing-page.php
  src/reset-password.php
  src/styles/dist/landing.css
  src/voter-login.php
Labels: enhancement, changes requested

#59 Email Functionality in Validation of Accounts
  src/includes/classes/email-sender.php
  src/includes/classes/query-handler.php
  src/includes/mailer.php
  src/manage-voters.php
  src/scripts/manage-voters.js
  src/styles/core.css
  src/styles/orgs/elite.css
  src/submission_handlers/select-email.php
  src/submission_handlers/validate-acc.php
  src/validate-voter.php
  src/voter-details.php
Labels: changes requested

#62 fix: AT1-72 ballot forms candidate preview & duties modals and others
  src/ballot-forms.php
  src/end-point.php
  src/feedback-suggestions.php
  src/scripts/ballot-forms.js
  src/scripts/feedback-suggestions.js
  src/styles/ballot-forms.css
  src/styles/feedback-suggestions.css
Labels: changes requested

#57 Updates on CAM Module
  src/admin-creation.php
  src/includes/components/sidebar.php
  src/manage-committee.php
  src/scripts/member-form-validation.js
  src/styles/admin-creation.css
  src/styles/manage-committee.css
  src/submission_handlers/add-member.php
  src/submission_handlers/manage-members.php
Labels: changes requested

#69 Error Reporting/Logging and Refactors on Login Authentication Script
  src/about-us.php
  src/includes/classes/session-manager.php
  src/includes/classes/voter-login-class.php
  src/includes/classes/voter-login-controller.php
  src/includes/error-logs.txt
  src/includes/error-reporting.php
  src/includes/process-reset-password.php
  src/includes/session-handler.php
Labels: enhancement

#92 Makeover of README.md
  README.md
Labels: documentation

#86 Mailing of Password Reset Request and Fixes on Approval Modal (VAM)
  src/includes/classes/email-sender.php
  src/includes/classes/landing-page-controller.php
  src/includes/classes/voter-login-class.php
  src/includes/send-password-reset.php
  src/includes/session-handler.php
  src/includes/voter-login-inc.php
  src/includes/voter-logout.php
  src/landing-page.php
  src/submission_handlers/validate-acc.php
  src/voter-login.php
Labels: patch

#94 BREAKING CHANGE[Database]: Voter Table Modification
  src/admindashboard.php
  src/ballot-forms.php
  src/includes/classes/voter-login-class.php
  src/includes/session-handler.php
  src/landing-page.php
  src/voter-login.php
Labels: impact alert, patch

#102 style: added the forgot password icon on reset password
  src/images/resc/icons/forgot-pass.png
  src/profile.php
  src/reset-password.php
  src/scripts/reset-password.js
  src/styles/dist/landing.css
  src/voter-login.php
Labels: enhancement
